In [20]:
from src.ingest import load_info, load_links
import pandas as pd

In [11]:
df_info = load_info()
df_info.head()

,string_protein_id,preferred_name,protein_size,annotation
0,9606.ENSP00000000233,ARF5,180,ADP-ribosylation factor 5; GTP-binding protein...
1,9606.ENSP00000000412,M6PR,277,Cation-dependent mannose-6-phosphate receptor;...
2,9606.ENSP00000001008,FKBP4,459,"Peptidyl-prolyl cis-trans isomerase FKBP4, N-t..."
3,9606.ENSP00000001146,CYP26B1,512,Cytochrome P450 26B1; Involved in the metaboli...
4,9606.ENSP00000002125,NDUFAF7,441,"Protein arginine methyltransferase NDUFAF7, mi..."

In [13]:
df_links = load_links()
df_links.head()

               protein1              protein2  combined_score
0  9606.ENSP00000000233  9606.ENSP00000356607             173
1  9606.ENSP00000000233  9606.ENSP00000427567             154
2  9606.ENSP00000000233  9606.ENSP00000253413             151
3  9606.ENSP00000000233  9606.ENSP00000493357             471
4  9606.ENSP00000000233  9606.ENSP00000324127             201

---
The following checks whether the link file contains each interaction once or twice:

In [17]:
a, b = df_links.iloc[0].protein1, df_links.iloc[0].protein2
print(a, b)
fwd = df_links[(df_links.protein1 == a) & (df_links.protein2 == b)]
rev = df_links[(df_links.protein1 == b) & (df_links.protein2 == a)]
print("forward:", len(fwd))
print("reverse:", len(rev))
print(fwd)
print(rev)

9606.ENSP00000000233 9606.ENSP00000356607
forward: 1
reverse: 1
               protein1              protein2  combined_score
0  9606.ENSP00000000233  9606.ENSP00000356607             173
                     protein1              protein2  combined_score
7352101  9606.ENSP00000356607  9606.ENSP00000000233             173

In [18]:
(df_links.protein1 < df_links.protein2).mean()

np.float64(0.5)

In [21]:
import numpy as np
a = df_links.protein1.to_numpy()
b = df_links.protein2.to_numpy()
swap = a > b
lo = np.where(swap, b, a)
hi = np.where(swap, a, b)
n_rows = len(df_links)
n_pairs = len(pd.DataFrame({"lo": lo, "hi": hi}).drop_duplicates())
print(n_rows, n_pairs, n_rows / n_pairs)

13715404 6857702 2.0

In [22]:
print(a)

['9606.ENSP00000000233' '9606.ENSP00000000233' '9606.ENSP00000000233' ...
 '9606.ENSP00000501317' '9606.ENSP00000501317' '9606.ENSP00000501317']